# Generated by Django 5.0.3 on 2024-03-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
            ],
        ),
    ]
