# Generated by Django 5.0.3 on 2024-03-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventFinder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
